### ISSUE TITLE
Blender 4.3 error 

### ISSUE THREAD

**Issue by BennyGovaerts** [tin2tin/2D_Asset_Generator#2] opened 2024-11-11 13:23 UTC
![image](https://github.com/user-attachments/assets/93d68409-d8db-4c08-b35c-a276323458be)

**Comment by tin2tin** [comment] 2024-11-13 18:20
@BennyGovaerts I hope that the installation errors are gone now. Could you check?

**Comment by BennyGovaerts** [comment] 2024-11-13 20:58
![image](https://github.com/user-attachments/assets/8b82a29a-4e97-4d0b-886f-99cdcef9b6de)
![image](https://github.com/user-attachments/assets/6f3cf7ed-e0ec-4774-9e44-2a3f4770bb85)
![image](https://github.com/user-attachments/assets/7afd1e6d-28dd-4311-8b69-ac26112626d2)
![image](https://github.com/user-attachments/assets/37f92705-23ce-4ec1-9ad1-6b773568720e)
![image](https://github.com/user-attachments/assets/53ac587b-efcf-41ba-9392-2bed5aa9d1c1)
![image](https://github.com/user-attachments/assets/bc55edeb-6d46-40c8-b13b-6ef1c00a8d2c)

**Comment by BennyGovaerts** [comment] 2024-11-13 20:59
Hmm, still some Errors

**Comment by BennyGovaerts** [comment] 2024-11-13 21:14
![image](https://github.com/user-attachments/assets/bb041db5-f6ba-469b-b61f-4a14e7267e16)

**Comment by tin2tin** [comment] 2024-11-13 21:15
@BennyGovaerts I don't see this error What is your OS, and CUDA number?

There are some people with a similar problem here: https://stackoverflow.com/questions/74594256/pytorch-error-loading-lib-site-packages-torch-lib-shm-dll-or-one-of-its-depen

Some suggest using: torch==2.2.1
If you want to try this, unzip, open ` __init__.py` and edit this line to that version, zip and then install: https://github.com/tin2tin/2D_Asset_Generator/blob/d777cf66dda18e450681145a45204950bc710d1e/__init__.py#L249

Or install: cudatoolkit https://developer.nvidia.com/cuda-toolkit

**Comment by BennyGovaerts** [comment] 2024-11-14 11:52
Windows 10 pro  64bit CPU Amd Ryzen 3950x 64GB Ram  - GPU RTX 4070 TI 16 GB 
![image](https://github.com/user-attachments/assets/99498f03-c0e8-445d-85ca-a2ffeead08fd)

![image](https://github.com/user-attachments/assets/d6aac5de-0f6a-4b2e-be8d-5f7516a9c83f)

Install cuda toolkit make no difference 

Is not that importent for me , i could install windows 11 but at the moment i have no time for this ( Sorry )

**Comment by tin2tin** [comment] 2024-11-27 20:23
@BennyGovaerts I did an update, forcing it to install torch==2.2.1. Does this work for you now?

**Comment by tin2tin** [comment] 2024-12-08 04:45
Will close this for now. If the problem is still happening, please reopen.

**Closed as completed by tin2tin** 2024-12-08 04:45 UTC
